HAI
	I HAS A NUM ITZ 5
	I HAS A WEE ITZ WIN
	I HAS A WORK

	NUM R 17							BTW NUM = 17
	WORK R SUM OF WEE AN NUM			BTW WORK = 18 (WEE will be implicitly typecasted to 1)
	VISIBLE "NUM is now " NUM
	VISIBLE "WORK is now " WORK
KTHXBYE