HAI
	I HAS A NUM ITZ 2		
	I HAS A FLOT ITZ 2.5	
	I HAS A NAME ITZ "erika"	
	I HAS A WEE ITZ WIN
	I HAS A WOO ITZ 12
	I HAS A WORK ITZ SUM OF SUM OF 3 AN 4 AN BIGGR OF 3 AN 6      BTW WORK = 13

BTW printing values:
	VISIBLE NUM							BTW NUM = 2
	VISIBLE FLOT						BTW FLOT = 2.5
	VISIBLE NAME						BTW NAME = "erika"
	VISIBLE 12							BTW 12
	VISIBLE WORK						BTW WORK = 13

KTHXBYE
